# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteNotificationSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemoteNotificationSampleApp
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end
